### ISSUE TITLE
`validate --update-context-products` no longer works with Solr upgrade

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#1034]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I run validate with the `--update-context-products` flag, I get an Exception

### 🕵️ Expected behavior

I expected the context products to be updated as expected

### 📜 To Reproduce

```
$ validate -u

org.apache.solr.client.solrj.impl.BaseHttpSolrClient$RemoteSolrException: Error from server at https://pds.nasa.gov/services/search/search?q=product_class%3AProduct_Context+AND+-data_class%3AResource+AND+-data_class%3APDS_Affiliate&qt=%2Fsearch&start=0&fl=identifier%2C+version_id%2C+data_product_type%2C+target_name%2C+instrument_name%2C+instrument_host_name%2C+resource_name%2C+investigation_name%2C+target_type%2C+instrument_type%2C+instrument_host_type%2C+resource_type%2C+investigation_type%2C+facility_name%2C+facility_type%2C+airborne_name%2C+airborne_type&wt=javabin&version=2: Expected mime type in [application/vnd.apache.solr.javabin, application/octet-stream] but got text/html. ��.responseHeader��+zkConnected�&status�%QTimeC�&params��!q?5product_class:Product_Context AND -data_class:Resource AND -data_class:PDS_Affiliate�"fl?�identifier, version_id, data_product_type, target_name, instrument_name, instrument_host_name, resource_name, investigation_name, target_type, instrument_type, instrument_host_type, resource_type, investigation_type, facility_name, facility_type, airborne_name, airborne_type�%start!0�"wt'javabin�(response
                                                                                                                            �u�`�
 ��*identifier�?"urn:nasa:pds:context:target:trans-neptunian_object.90568_2004_gv9?'urn:nasa:pds:context:target:trans-neptunian_object.90568_2004_gv9::1.0�+target_name�0(90568) 2004 GV9�1data_product_type�&Target�+target_type�6TRANS-NEPTUNIAN OBJECT�*version_id#1.0
         ��?$urn:nasa:pds:context:target:trans-neptunian_object.91133_1998_hk151?)urn:nasa:pds:context:target:trans-neptunian_object.91133_1998_hk151::1.0�2(91133) 1998 HK151�&Target�6TRANS-NEPTUNIAN OBJECT�#1.0
                                                                                   ��?#urn:nasa:pds:context:target:trans-neptunian_object.91205_1998_us43?(urn:nasa:pds:context:target:trans-neptunian_object.91205_1998_us43::1.0�1(91205) 1998 US43�&Target�6TRANS-NEPTUNIAN OBJECT�#1.0
                          ��?$urn:nasa:pds:context:target:trans-neptunian_object.91554_1999_rz215?)urn:nasa:pds:context:target:trans-neptunian_object.91554_1999_rz215::1.0�2(91554) 1999 RZ215�&Target�6TRANS-NEPTUNIAN OBJECT�#1.0
                                                                                                    ��?#urn:nasa:pds:context:target:trans-neptunian_object.95625_2002_gx32?(urn:nasa:pds:context:target:trans-neptunian_object.95625_2002_gx32::1.0�1(95625) 2002 GX32�&Target�6TRANS-NEPTUNIAN OBJECT�#1.0
                                           ��4instrument_host_name�/Cassini Orbiter�?urn:nasa:pds:context:instrument_host:spacecraft.co?urn:nasa:pds:context:instrument_host:spacecraft.co::1.3�/Instrument_Host�#1.3�4instrument_host_type�*Spacecraft
                                                                                                                       ���?Mars Atmosphere and Volatile Evolution (MAVEN)�?urn:nasa:pds:context:instrument_host:spacecraft.maven?rn:nasa:pds:context:instrument_host:spacecraft.maven::2.0�/Instrument_Host�#2.0�*Spacecraft
                                                            ���?Wide-Field Infrared Survey Explorer�?urn:nasa:pds:context:instrument_host:spacecraft.wise?urn:nasa:pds:context:instrument_host:spacecraft.wise::1.0�/Instrument_Host�#1.0�*Spacecraft
                                                                                                                     ���&MASCOT�?urn:jaxa:darts:context:instrument_host:lander.mascot?urn:jaxa:darts:context:instrument_host:lander.mascot::1.2�/Instrument_Host�#1.2�&Lander
             ���:MINERVA-II1 Rover-1a HIBOU�?urn:jaxa:darts:context:instrument_host:rover.minerva2-1_hibou?#urn:jaxa:darts:context:instrument_host:rover.minerva2-1_hibou::1.1�/Instrument_Host�#1.1�%Rover
                                                                           ���8MINERVA-II1 Rover-1b OWL�?urn:jaxa:darts:context:instrument_host:rover.minerva2-1_owl?!urn:jaxa:darts:context:instrument_host:rover.minerva2-1_owl::1.1�/Instrument_Host�#1.1�%Rover
   ���9MINERVA-II2 Rover-2 ULULA�?urn:jaxa:darts:context:instrument_host:rover.minerva2-2_ulula?#urn:jaxa:darts:context:instrument_host:rover.minerva2-2_ulula::1.1�/Instrument_Host�#1.1�%Rover
                                                                ���?APOLLO 11 EARLY APOLLO SCIENTIFIC EXPERIMENT PACKAGE�?urn:nasa:pds:context:instrument_host:spacecraft.a11e?urn:nasa:pds:context:instrument_host:spacecraft.a11e::1.1�/Instrument_Host�#1.1�*Spacecraft
          ���?
              APOLLO 12 LUNAR SURFACE EXPERIMENTS PACKAGE�?urn:nasa:pds:context:instrument_host:spacecraft.a12a?urn:nasa:pds:context:instrument_host:spacecraft.a12a::1.3�/Instrument_Host�#1.3�*Spacecraft
                                                                           ���?APOLLO 12 COMMAND AND SERVICE MODULE�?urn:nasa:pds:context:instrument_host:spacecraft.a12c?urn:nasa:pds:context:instrument_host:spacecraft.a12c::1.2�/Instrument_Host�#1.2�*Spacecraft
     ���6APOLLO 12 LUNAR MODULE�?urn:nasa:pds:context:instrument_host:spacecraft.a12l?urn:nasa:pds:context:instrument_host:spacecraft.a12l::1.2�/Instrument_Host�#1.2�*Spacecraft
                                                 ���?
                                                     APOLLO 14 LUNAR SURFACE EXPERIMENTS PACKAGE�?urn:nasa:pds:context:instrument_host:spacecraft.a14a?urn:nasa:pds:context:instrument_host:spacecraft.a14a::1.4�/Instrument_Host�#1.4�*Spacecraft
                                                                                                                  ���?APOLLO 14 COMMAND AND SERVICE MODULE�?urn:nasa:pds:context:instrument_host:spacecraft.a14c?urn:nasa:pds:context:instrument_host:spacecraft.a14c::1.2�/Instrument_Host�#1.2�*Spacecraft
                                            ���6APOLLO 14 LUNAR MODULE�?urn:nasa:pds:context:instrument_host:spacecraft.a14l?urn:nasa:pds:context:instrument_host:spacecraft.a14l::1.2�/Instrument_Host�#1.2�*Spacecraft
                                                                                        ���?
                                                                                            APOLLO 15 LUNAR SURFACE EXPERIMENTS PACKAGE�?urn:nasa:pds:context:instrument_host:spacecraft.a15a?urn:nasa:pds:context:instrument_host:spacecraft.a15a::1.3�/Instrument_Host�#1.3�*Spacecraft
                         ���?APOLLO 15 COMMAND AND SERVICE MODULE�?urn:nasa:pds:context:instrument_host:spacecraft.a15c?urn:nasa:pds:context:instrument_host:spacecraft.a15c::1.3�/Instrument_Host�#1.3�*Spacecraft
                                                                                   ���6APOLLO 15 LUNAR MODULE�?urn:nasa:pds:context:instrument_host:spacecraft.a15l?urn:nasa:pds:context:instrument_host:spacecraft.a15l::1.2�/Instrument_Host�#1.2�*Spacecraft
                                                                                                                               ���6APOLLO 15 SUBSATELLITE�?urn:nasa:pds:context:instrument_host:spacecraft.a15s?urn:nasa:pds:context:instrument_host:spacecraft.a15s::1.2�/Instrument_Host�#1.2�*Spacecraft
                                           ���?
                                               APOLLO 16 LUNAR SURFACE EXPERIMENTS PACKAGE�?urn:nasa:pds:context:instrument_host:spacecraft.a16a?urn:nasa:pds:context:instrument_host:spacecraft.a16a::1.3�/Instrument_Host�#1.3�*Spacecraft
                                                                                                            ���?APOLLO 16 COMMAND AND SERVICE MODULE�?urn:nasa:pds:context:instrument_host:spacecraft.a16c?urn:nasa:pds:context:instrument_host:spacecraft.a16c::1.3�/Instrument_Host�#1.3�*Spacecraft
                                      ���6APOLLO 16 LUNAR MODULE�?urn:nasa:pds:context:instrument_host:spacecraft.a16l?urn:nasa:pds:context:instrument_host:spacecraft.a16l::1.2�/Instrument_Host�#1.2�*Spacecraft
                                                                                  ���6APOLLO 16 SUBSATELLITE�?urn:nasa:pds:context:instrument_host:spacecraft.a16s?urn:nasa:pds:context:instrument_host:spacecraft.a16s::1.2�/Instrument_Host�#1.2�*Spacecraft
                                                                                                                              ���?
  APOLLO 17 LUNAR SURFACE EXPERIMENTS PACKAGE�?urn:nasa:pds:context:instrument_host:spacecraft.a17a?urn:nasa:pds:context:instrument_host:spacecraft.a17a::1.3�/Instrument_Host�#1.3�*Spacecraft
                                                               ���?APOLLO 17 COMMAND AND SERVICE MODULE�?urn:nasa:pds:context:instrument_host:spacecraft.a17c?urn:nasa:pds:context:instrument_host:spacecraft.a17c::1.2�/Instrument_Host�#1.2�*Spacecraft
                                                                                                                         ���6APOLLO 17 LUNAR MODULE�?urn:nasa:pds:context:instrument_host:spacecraft.a17l?urn:nasa:pds:context:instrument_host:spacecraft.a17l::1.2�/Instrument_Host�#1.2�*Spacecraft
                                     ���6APOLLO 17 SUBSATELLITE�?urn:nasa:pds:context:instrument_host:spacecraft.a17s?urn:nasa:pds:context:instrument_host:spacecraft.a17s::1.2�/Instrument_Host�#1.2�*Spacecraft
                                                                                 ���5CHANDRAYAAN-1 ORBITER�?urn:nasa:pds:context:instrument_host:spacecraft.ch1-orb?urn:nasa:pds:context:instrument_host:spacecraft.ch1-orb::1.2�/Instrument_Host�#1.2�*Spacecraft
  ���,CLEMENTINE 1�?urn:nasa:pds:context:instrument_host:spacecraft.clem1?rn:nasa:pds:context:instrument_host:spacecraft.clem1::1.3�/Instrument_Host�#1.3�*Spacecraft
                                     ���9Europa Clipper Spacecraft�?urn:nasa:pds:context:instrument_host:spacecraft.clipper?urn:nasa:pds:context:instrument_host:spacecraft.clipper::1.1�/Instrument_Host�#1.1�*Spacecraft
                                                                                          ���?
                                                                                              CLPS Task Order 2 AB Peregrine Lunar Lander�? urn:nasa:pds:context:instrument_host:spacecraft.clps_to_2ab_pll?%urn:nasa:pds:context:instrument_host:spacecraft.clps_to_2ab_pll::1.1�/Instrument_Host�#1.1�&Lander
                                               ���2COMET NUCLEUS TOUR�?urn:nasa:pds:context:instrument_host:spacecraft.con?urn:nasa:pds:context:instrument_host:spacecraft.con::1.2�/Instrument_Host�#1.2�*Spacecraft
                                                                                     ��?urn:nasa:pds:context:instrument_host:spacecraft.dart?urn:nasa:pds:context:instrument_host:spacecraft.dart::1.2�/Instrument_Host�#1.2�*Spacecraft
                                                                                                        ���$DAWN�?urn:nasa:pds:context:instrument_host:spacecraft.dawn?urn:nasa:pds:context:instrument_host:spacecraft.dawn::1.3�/Instrument_Host�#1.3�*Spacecraft
  ���;DCAM3 (Deployable Camera 3)�?urn:jaxa:darts:context:instrument_host:spacecraft.dcam3?urn:jaxa:darts:context:instrument_host:spacecraft.dcam3::1.1�/Instrument_Host�#1.1�*Spacecraft
                                                         ���<DEEP IMPACT FLYBY SPACECRAFT�?urn:nasa:pds:context:instrument_host:spacecraft.dif?urn:nasa:pds:context:instrument_host:spacecraft.dif::1.3�/Instrument_Host�#1.3�*Spacecraft
                                                                                                         ���?DEEP IMPACT IMPACTOR SPACECRAFT�?urn:nasa:pds:context:instrument_host:spacecraft.dii?urn:nasa:pds:context:instrument_host:spacecraft.dii::1.3�/Instrument_Host�#1.3�*Spacecraft
                            ���,DEEP SPACE 1�?urn:nasa:pds:context:instrument_host:spacecraft.ds1?urn:nasa:pds:context:instrument_host:spacecraft.ds1::1.3�/Instrument_Host�#1.3�*Spacecraft
                                                            ���&GIOTTO�?urn:esa:psa:context:instrument_host:spacecraft.gio?urn:esa:psa:context:instrument_host:spacecraft.gio::1.1�/Instrument_Host�#1.1�*Spacecraft
                                                                                    ���/GALILEO ORBITER�?urn:nasa:pds:context:instrument_host:spacecraft.go?urn:nasa:pds:context:instrument_host:spacecraft.go::1.3�/Instrument_Host�#1.3�*Spacecraft
                                                                                                                     ���-GALILEO PROBE�?urn:nasa:pds:context:instrument_host:spacecraft.gp?urn:nasa:pds:context:instrument_host:spacecraft.gp::1.2�/Instrument_Host�#1.2�*Spacecraft
                    ���?
                        GRAVITY RECOVERY AND INTERIOR LABORATORY A�?urn:nasa:pds:context:instrument_host:spacecraft.grail-a?urn:nasa:pds:context:instrument_host:spacecraft.grail-a::1.3�/Instrument_Host�#1.3�*Spacecraft
                                                                                          ���?
                                                                                              GRAVITY RECOVERY AND INTERIOR LABORATORY B�?urn:nasa:pds:context:instrument_host:spacecraft.grail-b?urn:nasa:pds:context:instrument_host:spacecraft.grail-b::1.3�/Instrument_Host�#1.3�*Spacecraft
                                ���(Hayabusa�?urn:nasa:pds:context:instrument_host:spacecraft.hay?urn:nasa:pds:context:instrument_host:spacecraft.hay::2.1�/Instrument_Host�#2.1�*Spacecraft
                                                            ���-HUYGENS PROBE�?urn:esa:psa:context:instrument_host:spacecraft.hp?urn:esa:psa:context:instrument_host:spacecraft.hp::1.1�/Instrument_Host�#1.1�*Spacecraft
                                                                                         ���6HUBBLE SPACE TELESCOPE�?urn:nasa:pds:context:instrument_host:spacecraft.hst?urn:nasa:pds:context:instrument_host:spacecraft.hst::1.4�/Instrument_Host�#1.4�*Spacecraft�,facet_counts��-facet_queries��,facet_fields��7facet_pds_model_version��&1,pds4U��,facet_agency��&1,nasaU��*facet_type��(1,target]\�,1,instrumentP0�+1,telescopeX	�/1,investigationY�11,instrument_hostT�*1,facilityR�*1,airborneA�,facet_target��*1,asteroidW�+1,satellite_�'1,otherS�-1,calibrationP�(1,planetH�81,trans-neptunian objectA�3facet_investigation�E�+1,apollo 11A�+1,apollo 12A�+1,apollo 14A�+1,apollo 15A�+1,apollo 16A�+1,apollo 17A�?1,arecibo radar imaging and doppler spectroscopyA�?1,astromaterial geochemical dataA�?1,b. campbell venus earth-based radar observationsA�?+1,balloon observation platform for planetary science (bopps) - 2014 flightA�11,cassini-huygensA�/1,chandrayaan-1A�51,clps task order 2abA�=1,comet sl9/jupiter collisionA�?1,commercial lunar payload services (clps) initiativeA�11,contour missionA�?1,dawn mission to vesta and ceresA�-1,deep impactA�.1,deep space 1A�1,deep space program science experimentA�?1,double asteroid redirection testA�71,dsn media calibrationA�?1,dust devil field campaign, eldorado playa, nevada, 2015A�?!1,earth-based observations of uranus system stellar occultationsA�'1,epoxiA�81,europa clipper missionA�91,frankenspectra databaseA�)1,galileoA�)1,geodesyA�(1,giottoA�91,giotto extended missionA�?
                                                                                                               1,gravity recovery and interior laboratoryA�21,hayabusa missionA�?
                                                 1,hayabusa2 asteroid sample return missionA�61,hot_ion_atmos_escapeA�%1,hstA�01,insight landerA�?1,international cometary explorerA�?1,international rosetta missionA�?1,investigation of laboratory shocked feldsparsA�.1,iras missionA�<1,irtf io observing campaignA�%1,iueA�&1,junoA�<1,jupiter support monitoringA�(1,kaguyaA�?1,korea pathfinder lunar orbiterA�91,lab.hydrocarbon_spectraA�'1,ladeeA�+1,liciacubeA�?1,lowell observatory near-earth object surveyA�?1,lowell_uranus-neptune-photometryA�&1,lucyA�?1,lunar crater observation and sensing satelliteA�21,lunar prospectorA�>1,lunar reconnaissance orbiterA�?+1,lunar simulants jsc-1a and lms-1 far-ultraviolet reflectance data bundleA�31,lunar trailblazerA�*1,magellanA�,1,mariner 10A�,1,mariner 69A�+1,mariner71A�?1,mars 2020: perseverance roverA�?	1,mars atmosphere and volatile evolutionA�?1,mars exploration rovers: spirit and opportunityA�.1,mars expressA�61,mars global surveyorA�/1,mars observerA�.1,mars odysseyA�11,mars pathfinderA�.1,mars phoenixA�=1,mars reconnaissance orbiterA�?
                                                                         1,mars science laboratory: curiosity roverA�?#1,material properties of organic liquids, ices, and hazes on titanA�71,mcmath-pierce_mercuryA�+1,messengerA�<1,midcourse space experimentA�?1,near earth asteroid rendezvousA�&1,neasA�)1,neowiseA�.1,new horizonsA�?
                                                                            1,new horizons kuiper belt extended missionA�?1,new horizons kuiper belt extended mission 2A�&1,nextA�;1,no specific investigationA�,1,osiris-rexA�*1,phobos 2A�)1,pioneerA�,1,pioneer 10A�,1,pioneer 11A�+1,pioneer 8A�+1,pioneer 9A�/1,pioneer venusA�.1,pre-magellanA�(1,psycheA�?,r. greeley field investigation, amboy crater, californiaA�81,relab spectral libraryA�*1,sakigakeA�?1,saturn ring plane crossing 1995A�?1,saturn small satellite astrometryA�0facet_instrument��(1,cameraR�.1,spectrometerX�/1,radio scienceR�11,plasma analyzerX�.1,magnetometerT�31,particle detectorS�/1,dust analyzerM�J�,1,photometerI�/1,accelerometerH�-1,meteorologyF�+1,altimeterE�61,imaging spectrometerE�,1,radiometerE�51,cosmic ray detectorD�/1,reflectometerC�41,radio spectrometerB�01,detector arrayA�,1,solar windA�<facet_primary_result_purpose��?facet_primary_result_processing_level��,facet_ranges��/facet_intervals��.facet_heatmaps�
	at org.apache.solr.client.solrj.impl.HttpSolrClientBase.checkContentType(HttpSolrClientBase.java:356)
	at org.apache.solr.client.solrj.impl.HttpSolrClientBase.processErrorsAndResponse(HttpSolrClientBase.java:242)
	at org.apache.solr.client.solrj.impl.Http2SolrClient.processErrorsAndResponse(Http2SolrClient.java:570)
	at org.apache.solr.client.solrj.impl.Http2SolrClient.request(Http2SolrClient.java:526)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:255)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:927)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:940)
	at gov.nasa.pds.validate.ValidateLauncher.getLatestJsonContext(ValidateLauncher.java:532)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1707)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1783)
```

**Comment by jordanpadams** [comment]
https://github.com/NASA-PDS/validate/pull/1036
