### ISSUE TITLE
Validate does not correctly pass PDF/A files that are in a subdirectory

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS-Incubator/validate#447]
## 🐛 Describe the bug
Validate will erroneously give a warning that a file is not PDF/A compliant if the file is in a subdirectory, and there is another file in the parent directory.

## 📜 To Reproduce

Using the attached sample file, which has this layout:

* document/
  * mission_phase_plans/
    * Preliminary_Survey_Phase_Plan_Narrative.xml
    * Preliminary_Survey_Phase_Plan_Narrative.pdf
  * orex_ldd_description_doc.pdf
  * orex_ldd_description_doc.xml

run `validate document` from the directory above document. It will produce the attached output, which includes the following warning:

```
  PASS: file:/Users/jessestone/Desktop/validate_pdfa_bug/document/mission_phase_plans/Preliminary_Survey_Phase_Plan_Narrative.xml
      WARNING  [warning.pdf.file.not_pdfa_compliant]   file:/Users/jessestone/Desktop/validate_pdfa_bug/document/mission_phase_plans/Preliminary_Survey_Phase_Plan_Narrative.pdf is not valid PDF/A file or does not exist
```

However, if you validate the `mission_phase_plans` directory from within the document directory by running `validate mission_phase_plans`, the output will not include the warning.

```
  PASS: file:/Users/jessestone/Desktop/validate_pdfa_bug/document/mission_phase_plans/Preliminary_Survey_Phase_Plan_Narrative.xml
        1 product validation(s) completed
```

The same happens if you validate the document directly.

## 🕵️ Expected behavior
The validator should accurately detect whether the file is a valid PDF/A regardless of where it is run from. In this case, the file is definitely valid- I independently verified it using VeraPDF.

## 📚 Version of Software Used
```
gov.nasa.pds:validate
Version 2.1.0
Release Date: 2021-10-05 10:20:49
```

## 🩺 Test Data / Additional context

I suspect that the issue is caused by the validator looking in the wrong location for the PDF file. Removing the document from the parent directory also causes the document in the subdirectory to pass validation.

[document.zip](https://github.com/NASA-PDS/validate/files/7589692/document.zip)
[failing_output.txt](https://github.com/NASA-PDS/validate/files/7589693/failing_output.txt)
[passing_output_2.txt](https://github.com/NASA-PDS/validate/files/7589694/passing_output_2.txt)
[passing_output.txt](https://github.com/NASA-PDS/validate/files/7589695/passing_output.txt)

## 🖥 System Info

---

**Comment by qchaupds** [comment]
Using the document.zip file produced by @jstone-psi I am not able to re-produce the error.  Both of the below runs ran fine with the DEV code as of 11/23/2021.  The code has not been merged back into the main branch nor deployed.

```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 110 % validate -R pds4.label -r report_github447_label_valid_1.json   -s json -t  src/test/resources/github447/document/orex_ldd_description_doc.xml >& t1

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 111 % egrep "label|status|message" report_github447_label_valid_1.json
    "ruleType": "pds4.label",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github447/document/orex_ldd_description_doc.xml",
      "messages": [],
    "messageTypes": []

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 112 % validate -R pds4.label -r report_github447_label_valid_2.json   -s json -t  src/test/resources/github447/document/mission_phase_plans/Preliminary_Survey_Phase_Plan_Narrative.xml >& t2

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 113 % egrep "label|status|message" report_github447_label_valid_2.json
    "ruleType": "pds4.label",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github447/document/mission_phase_plans/Preliminary_Survey_Phase_Plan_Narrative.xml",
      "messages": [],
    "messageTypes": []

```

**Comment by jstone-psi** [comment]
@qchaupds It looks like you are running validate on the individual products. If you run it on the entire document directory, then the error should surface.

**Comment by qchaupds** [comment]
So it looks like the bug is found.  Will see how to fix it for @jstone-psi issue raised.

Message for current and future developer(s) if time runs out.

Adding lines 128 to print the stack trace and 131 to allow the code to exit

```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 104 % vi ./src/main/java/gov/nasa/pds/tools/util/PDFUtil.java

 97   private boolean validatePDF(URI uri, String pdfRef) {
 98     boolean pdfValidateFlag = false;
 99 
100     // Create a parser and auto-detect flavour
101     try {
102         PDFAParser parser = Foundries.defaultInstance().createParser(new FileInputStream(pdfRef));
103         PDFAFlavour detectedFlavour = parser.getFlavour();
104         LOG.debug("validatePDF: parser.getFlavour() [{}]", detectedFlavour);
105 
106         // First, check the flavour is valid 1a or 1b
107         if (!detectedFlavour.equals(PDFAFlavour.PDFA_1_A) && !detectedFlavour.equals(PDFAFlavour.PDFA_1_B)) {
108           this.errorMessage = "Invalid PDF/A version detected for " + uri + ". Expected: 1a or 1b. Actual: " + detectedFlavour.getId();
109         } else {
110           // Next, check the PDF is actually a valid 1a/1b flavour 
111           PDFAValidator validator = Foundries.defaultInstance().createValidator(detectedFlavour, false);
112           this.parserFlavor = parser.getFlavour().getId();
113           ValidationResult result = validator.validate(parser);
114           if (result.isCompliant()) {
115               // File is a valid PDF
116               LOG.debug("validatePDF file " + pdfRef + " is a valid PDF file with flavor " + parser.getFlavour().getId());
117               pdfValidateFlag = true;
118           } else {
119               LOG.error("validatePDF file" + pdfRef + " is not valid PDF file with flavor " + parser.getFlavour().getId());
120 
121               // Write the result to external file so the user can look over in the validate report.
122               this.writeErrorToFile(uri, result, parser.getFlavour().getId());
123 
124               this.errorMessage = "Validation failed for flavour PDF/A-" + detectedFlavour.getId() + ".  Detailed error output can be found at " + this.getExternalErrorFilename();
125           }
126         }
127     } catch (Exception e) {
128         e.printStackTrace();
129         LOG.error("validatePDF parse PDF file " + pdfRef);
130         LOG.error("validatePDF is " + e.getMessage());
131         System.exit(0);
132     }
133     return(pdfValidateFlag);
134   }

```
We can see the the actual name of the PDF file is missing a sub directory.
```
[pool-2-thread-1] DEBUG gov.nasa.pds.tools.util.PDFUtil - validateFileStandardConformity:parent,pdfBase,pdfRef [/home/qchau/sandbox/validate/src/test/resources/github447/document],[Preliminary_Survey_Phase_Plan_Narrative.pdf],[/home/qchau/sandbox/validate/src/test/resources/github447/document/Preliminary_Survey_Phase_Plan_Narrative.pdf]
java.io.FileNotFoundException: /home/qchau/sandbox/validate/src/test/resources/github447/document/Preliminary_Survey_Phase_Plan_Narrative.pdf (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at gov.nasa.pds.tools.util.PDFUtil.validatePDF(PDFUtil.java:102)
        at gov.nasa.pds.tools.util.PDFUtil.validateFileStandardConformity(PDFUtil.java:170)
        at gov.nasa.pds.tools.validate.rule.pds4.FileReferenceValidationRule.handlePDF(FileReferenceValidationRule.java:738)
        at gov.nasa.pds.tools.validate.rule.pds4.FileReferenceValidationRule.validate(FileReferenceValidationRule.java:410)
        at gov.nasa.pds.tools.validate.rule.pds4.FileReferenceValidationRule.validateFileReferences(FileReferenceValidationRule.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
        at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:153)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[pool-2-thread-1] ERROR gov.nasa.pds.tools.util.PDFUtil - validatePDF parse PDF file /home/qchau/sandbox/validate/src/test/resources/github447/document/Preliminary_Survey_Phase_Plan_Narrative.pdf
[pool-2-thread-1] ERROR gov.nasa.pds.tools.util.PDFUtil - validatePDF is /home/qchau/sandbox/validate/src/test/resources/github447/document/Preliminary_Survey_Phase_Plan_Narrative.pdf (No such file or directory)

```

The fix is to figure out where the label is in the directory structure and then passing the appropriate sub directory to the function that does the PDF validation.

**Comment by qchaupds** [comment]
Added more debug printing in validateFileStandardConformity() function in src/main/java/gov/nasa/pds/tools/util/PDFUtil.java reveals that these 2 lines are returning false parent at line 162 and 163, which causes the pdfRef to point to a non-existence PDF file:

162     File file = new File(uri.getPath());
163     String parent = file.getParent();
164 
165     // Build the full pathname of the PDF file.
166     String pdfRef = parent + File.separator + pdfBase;
167     LOG.debug("validateFileStandardConformity:parent,pdfBase,pdfRef [{}],[{}],[{}]",parent,pdfBase,pdfRef);
168 
169     // First, validate the PDF against PDFAFlavour.PDFA_1_A, if it does not validate, do it again with PDFAFlavour.PDFA_1_B
170     pdfValidateFlag = this.validatePDF(uri, pdfRef);


```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 106 % grep validateFileStandardConformity t3
[pool-1-thread-1] DEBUG gov.nasa.pds.tools.util.PDFUtil - validateFileStandardConformity:pdfBase orex_ldd_description_doc.pdf
[pool-1-thread-1] DEBUG gov.nasa.pds.tools.util.PDFUtil - validateFileStandardConformity:parent,pdfBase,pdfRef [/home/qchau/sandbox/validate/src/test/resources/github447/document],[orex_ldd_description_doc.pdf],[/home/qchau/sandbox/validate/src/test/resources/github447/document/orex_ldd_description_doc.pdf]
[pool-1-thread-1] DEBUG gov.nasa.pds.tools.util.PDFUtil - validateFileStandardConformity:pdfRef,pdfValidateFlag [/home/qchau/sandbox/validate/src/test/resources/github447/document],true
[pool-2-thread-1] DEBUG gov.nasa.pds.tools.util.PDFUtil - validateFileStandardConformity:pdfBase Preliminary_Survey_Phase_Plan_Narrative.pdf
[pool-2-thread-1] DEBUG gov.nasa.pds.tools.util.PDFUtil - validateFileStandardConformity:parent,pdfBase,pdfRef [/home/qchau/sandbox/validate/src/test/resources/github447/document],[Preliminary_Survey_Phase_Plan_Narrative.pdf],[/home/qchau/sandbox/validate/src/test/resources/github447/document/Preliminary_Survey_Phase_Plan_Narrative.pdf]
        at gov.nasa.pds.tools.util.PDFUtil.validateFileStandardConformity(PDFUtil.java:170)
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 107 % 
```

**Comment by qchaupds** [comment]
Some good news from DEV.  So with the below changes in two files, the bug have disappeared.  The fix has to do with passing the parent to validateFileStandardConformity(String pdfBase, URL parentURL) function so it can use the correct parent to build the URL of the actual PDF file.

```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 118 % git diff src/main/java/gov/nasa/pds/tools/util/PDFUtil.java
diff --git a/src/main/java/gov/nasa/pds/tools/util/PDFUtil.java b/src/main/java/gov/nasa/pds/tools/util/PDFUtil.java
index 052d81f..c0ce8d1 100644
--- a/src/main/java/gov/nasa/pds/tools/util/PDFUtil.java
+++ b/src/main/java/gov/nasa/pds/tools/util/PDFUtil.java
@@ -125,8 +125,10 @@ public class PDFUtil {
           }
         }
     } catch (Exception e) {
+        e.printStackTrace();
         LOG.error("validatePDF parse PDF file " + pdfRef);
         LOG.error("validatePDF is " + e.getMessage());
+        System.exit(0);
     }
     return(pdfValidateFlag);
   }
@@ -138,7 +140,7 @@ public class PDFUtil {
    * @return true if the PDF is PDF/A compliant, and false otherwise
    *
    */
-  public synchronized boolean validateFileStandardConformity(String pdfBase) throws Exception {
+  public synchronized boolean validateFileStandardConformity(String pdfBase, URL parentURL) throws Exception {
     // Do the validation of the PDF document.
     // https://verapdf.org/category/software/
 
@@ -157,12 +159,17 @@ public class PDFUtil {
       throw new Exception("validateFileStandardConformity:Cannot build URI for target [" + getTarget() + "]");
     }
 
-    File file = new File(uri.getPath());
-    String parent = file.getParent();
+    //File file = new File(uri.getPath());
+    //String parent = file.getParent();
+    // Get the parent from parentURL instead of using the above two lines will only get the top level directory.
+    String parent = parentURL.getFile();
 
     // Build the full pathname of the PDF file.
     String pdfRef = parent + File.separator + pdfBase;
     LOG.debug("validateFileStandardConformity:parent,pdfBase,pdfRef [{}],[{}],[{}]",parent,pdfBase,pdfRef);
+    LOG.debug("validateFileStandardConformity:parent,pdfBase,pdfRef,uri [{}],[{}],[{}],{}",parent,pdfBase,pdfRef,uri);
+    //System.out.println("early#exit(0)");
+    //System.exit(0);
 
     // First, validate the PDF against PDFAFlavour.PDFA_1_A, if it does not validate, do it again with PDFAFlavour.PDFA_1_B
     pdfValidateFlag = this.validatePDF(uri, pdfRef);

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 119 % git diff  src/main/java/gov/nasa/pds/tools/validate/rule/pds4/FileReferenceValidationRule.java
diff --git a/src/main/java/gov/nasa/pds/tools/validate/rule/pds4/FileReferenceValidationRule.java b/src/main/java/gov/nasa/pds/tools/validate/rule/pds4/FileReferenceValidationRule.java
index ed36e86..a0a05fd 100644
--- a/src/main/java/gov/nasa/pds/tools/validate/rule/pds4/FileReferenceValidationRule.java
+++ b/src/main/java/gov/nasa/pds/tools/validate/rule/pds4/FileReferenceValidationRule.java
@@ -407,6 +407,8 @@ public class FileReferenceValidationRule extends AbstractValidationRule {
                   if ((doctype.equalsIgnoreCase("PDF/A")) || (doctype.equalsIgnoreCase("PDF"))) {
                      // Check for PDF file validity.
                     try {
+
+// The value of parent is wrong.  It is the top level directory but the actual parent is some where a few directory down.
                       problems.addAll(handlePDF(target, urlRef,
                           fileObject, filename, parent, directory));
                     } catch (Exception e) {
@@ -707,6 +709,7 @@ public class FileReferenceValidationRule extends AbstractValidationRule {
                                             TinyNodeImpl fileObject, String pdfName, URL parent, String directory)
   throws Exception {
     LOG.debug("handlePDF:target,fileRef,pdfName {},{},{}",target,fileRef,pdfName);
+    LOG.debug("handlePDF:target,fileRef,pdfName,parent {},{},{},{}",target,fileRef,pdfName,parent);
     boolean pdfValidateFlag = false;
     if ((pdfName == null) || (fileObject == null)) {
         if (pdfName == null) {
@@ -735,7 +738,7 @@ public class FileReferenceValidationRule extends AbstractValidationRule {
         // First, let's check the filename even makes sense
         DocumentsChecker check = new DocumentsChecker();
         if (check.isMimeTypeCorrect(fileRef.toString(), "PDF/A")) {
-          pdfValidateFlag = this.pdfUtil.validateFileStandardConformity(pdfName);
+          pdfValidateFlag = this.pdfUtil.validateFileStandardConformity(pdfName,parent);
   
           // Report an error if the PDF file is not PDF/A compliant.
           if (!pdfValidateFlag) {
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 120 % 
```

Running validate again pointing to a directory resulted in a good run.

```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 118 %  validate -r report_github447_valid_3.json   -s json -t  src/test/resources/github447/document >& t3

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 119 %  egrep "label|status|message" report_github447_valid_3.json
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github447/document/orex_ldd_description_doc.xml",
      "messages": [],
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github447/document/mission_phase_plans/Preliminary_Survey_Phase_Plan_Narrative.xml",
      "messages": [],
    "messageTypes": []

```
