### ISSUE TITLE
NullPointerException when Table_Delimited is missing records attribute

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#473]
## 🐛 Describe the bug

NullPointerException thrown on invalid label. The software should fail gracefully with an error, not throw an uncaught exception. Reported by B. Deen.

## 📜 To Reproduce
```
% validate-2.1.4/bin//validate -target !* --report-file !*.valrpt --schematron /project/m20/rgd/pds4/validate/dd//*.sch --schema /project/m20/rgd/pds4/validate/dd//*.xsd

% valgo mech_drive.csv.xml
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.task.ValidationTask.execute(ValidationTask.java:133)
	at gov.nasa.pds.tools.validate.task.BlockingTaskManager.submit(BlockingTaskManager.java:27)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:275)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1333)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1590)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1636)
Caused by: java.lang.NullPointerException
	at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataContentValidationRule.java:951)
	... 12 more
```

## 🕵️ Expected behavior

Expected validation report:
```
PDS Validate Tool Report

Configuration:
   Version                       2.1.5-SNAPSHOT
   Date                          2022-01-28T00:42:48Z

Parameters:
   Targets                       [file:/Users/jpadams/Downloads/mech_drive.csv.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       off
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/validate-2.1.5-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  FAIL: file:/Users/jpadams/Downloads/mech_drive.csv.xml
      ERROR  [error.label.schema]   line 18, 17: cvc-pattern-valid: Value '3.0.0' is not facet-valid with respect to pattern '([0-9]+)(\.){1}([0-9]+)' for type 'version_id'.
      ERROR  [error.label.schema]   line 18, 17: cvc-type.3.1.3: The value '3.0.0' of element 'version_id' is not valid.
      ERROR  [error.label.schema]   line 94, 25: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://pds.nasa.gov/pds4/pds/v1":record_delimiter}'. One of '{"http://pds.nasa.gov/pds4/pds/v1":records}' is expected.
      ERROR  [error.label.schema]   line 96, 25: cvc-complex-type.2.4.b: The content of element 'Record_Delimited' is not complete. One of '{"http://pds.nasa.gov/pds4/pds/v1":maximum_record_length, "http://pds.nasa.gov/pds4/pds/v1":Field_Delimited, "http://pds.nasa.gov/pds4/pds/v1":Group_Field_Delimited}' is expected.
      ERROR  [error.label.schematron]   line 96, 25: The values for 'fields' and 'groups' must not both be '0'.  The number of fields found: (0).  The number of groups found: (0).
        1 product validation(s) completed

Summary:

  5 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    4            error.label.schema
    1            error.label.schematron

End of Report
Completed execution in 7720 ms
```

## 📚 Version of Software Used

2.1.4

## 🩺 Test Data / Additional context

[mech_drive.csv.txt](https://github.com/NASA-PDS/validate/files/7954872/mech_drive.csv.txt)
[mech_drive.csv.xml.txt](https://github.com/NASA-PDS/validate/files/7954873/mech_drive.csv.xml.txt)

**Comment by jordanpadams** [comment]
since the label is invalid, the critical failure is not ideal, but this is not a critical bug fix

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4212016
