### ISSUE TITLE
validate having issues checking some file content on windows

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#507]
## 🐛 Describe the bug

From user:
> I was test running version 2.2.0 of validate to see if it fixed the problem I previously reported. It seems to be working. But I am getting lots of messages on my terminal that I don’t understand. A short capture of the terminal is listed below.
 
```
Q:\stage\lunar\aamigration\diviner_rdr>Q:\stage\tools\pds4_validate\validate-2.2.0\bin\validate -v2 -C catalog_v02.xml -
R pds4.bundle -r xtest_con.txt -t Q:\stage\lunar\aamigration\diviner_rdr\bundle_test >xlog.txt
java.io.FileNotFoundException: null\201401112330_rdr.tab (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.getFirstLineLength(TableDataContentValid
ationRule.java:614)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.isTableLineOriented(TableDataContentVali
dationRule.java:656)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataConte
ntValidationRule.java:1111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
        at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:151)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.io.FileNotFoundException: null\201401111410_rdr.tab (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.getFirstLineLength(TableDataContentValid
ationRule.java:614)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.isTableLineOriented(TableDataContentVali
dationRule.java:656)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataConte
ntValidationRule.java:1111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
        at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:151)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.io.FileNotFoundException: null\201401111950_rdr.tab (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.getFirstLineLength(TableDataContentValid
ationRule.java:614)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.isTableLineOriented(TableDataContentVali
dationRule.java:656)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataConte
ntValidationRule.java:1111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
        at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:151)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

## 🕵️ Expected behavior

Reads in file successfully

## 📚 Version of Software Used

2.2.0

## 🩺 Test Data / Additional context

Any table data on windows

## 🖥 System Info
Windows

---

## 🦄 Related requirements
Same as https://github.com/NASA-PDS/validate/issues/503

**Comment by jpl-jengelke** [comment]
@jordanpadams: Is there separate test data for this or can we test with validate #503 ?

**Comment by jordanpadams** [comment]
@jpl-jengelke just any data on windows
