### ISSUE TITLE
--spot-check-data flag throws IOException

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#554]
## 🐛 Describe the bug

`--spot-check-data` flag seems to no longer work with latest upgrades to validate/pds4-jparser

## 📜 To Reproduce
```
validate --spot-check-data 5 -t src/test/resources/github480/test_success.xml
```
```
java.io.IOException: Error occurred while reading data object '1', record '6'
	at gov.nasa.pds.tools.validate.rule.pds4.TableValidator.validateTableDelimitedContent(TableValidator.java:263)
	at gov.nasa.pds.tools.validate.rule.pds4.TableValidator.validateDataObjectContents(TableValidator.java:160)
	at gov.nasa.pds.tools.validate.rule.pds4.TableValidator.validate(TableValidator.java:98)
	at gov.nasa.pds.tools.validate.rule.pds4.DataDefinitionAndContentValidationRule.validate(DataDefinitionAndContentValidationRule.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:64)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.task.ValidationTask.execute(ValidationTask.java:130)
	at gov.nasa.pds.tools.validate.task.BlockingTaskManager.submit(BlockingTaskManager.java:26)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:284)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1402)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1688)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1737)
java.io.IOException: Error occurred while reading data object '3', record '51'
	at gov.nasa.pds.tools.validate.rule.pds4.TableValidator.validateTableDelimitedContent(TableValidator.java:263)
	at gov.nasa.pds.tools.validate.rule.pds4.TableValidator.validateDataObjectContents(TableValidator.java:160)
	at gov.nasa.pds.tools.validate.rule.pds4.TableValidator.validate(TableValidator.java:98)
	at gov.nasa.pds.tools.validate.rule.pds4.DataDefinitionAndContentValidationRule.validate(DataDefinitionAndContentValidationRule.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:64)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.task.ValidationTask.execute(ValidationTask.java:130)
	at gov.nasa.pds.tools.validate.task.BlockingTaskManager.submit(BlockingTaskManager.java:26)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:284)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1402)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1688)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1737)

PDS Validate Tool Report

Configuration:
   Version                       3.1.0-SNAPSHOT
   Date                          2022-11-16T20:14:16Z

Parameters:
   Targets                       [file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github480/test_success.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Data Spot Check               5
   Max Errors                    100000
   Registered Contexts File      /Users/jpadams/proj/pds/pdsen/workspace/validate/validate-3.1.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  FAIL: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github480/test_success.xml
    Begin Content Validation: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github480/test.tab
      ERROR  [error.table.field_value_data_type_mismatch]   data object 3, record 11, field 1: Value does not match its data type 'ASCII_Integer': '8.' does not match the pattern '[+-]?\d+'
      ERROR  [error.table.field_value_data_type_mismatch]   data object 3, record 31, field 1: Value does not match its data type 'ASCII_Integer': '6.' does not match the pattern '[+-]?\d+'
    End Content Validation: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github480/test.tab
        1 product validation(s) completed

Summary:

  2 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    2            error.table.field_value_data_type_mismatch

End of Report
Completed execution in 6090 ms
```

## 🕵️ Expected behavior

Executes successfully

## 📚 Version of Software Used

v3.0.3

## 🩺 Test Data / Additional context

See `src/test/resources/github480/test_success.xml`

---

## ⚙️ Engineering Details
NOTE: Even though this file says "success" it fails when executing with content validation enabled. But it should still not throw an IOException. We should be able to find another data file in the repo to test again that actually runs successfully with `--spot-check-data`

**Comment by gxtchen** [comment]
@jordanpadams can you share the test file src/test/resources/github480/test_success.xml?

**Comment by jordanpadams** [comment]
@gxtchen that test data is here:  https://github.com/NASA-PDS/validate/tree/main/src/test/resources/github480 

that being said, I would recommend using that test data as an example to come up with more complex / corner case test cases.

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4123556
