### ISSUE TITLE
Upgrade validate-refs to work with new AOSS registry

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/validate#621]
## 💡 Description

Blocked by https://github.com/NASA-PDS/registry/issues/350

## Engineering Details
This MUST be hard-coded into the validate-refs code. The user will not be specifying which indices to query. We can add a specific flag to support overriding this, but otherwise it should be supported by the code, not the configuration provided by the end user.

**Comment by jordanpadams** [comment]
moving this to future sprint since this is blocked by https://github.com/NASA-PDS/registry/issues/350

**Comment by jordanpadams** [comment]
Per separate email discussions on https://github.com/NASA-PDS/registry/issues/350, this may be unblocked. Validate will need to be updated to support multiple indexes.

Is there a way to perform this operation in the OpenSearch Java API in order to get the known registry indices?

```
GET /_cat/indices?format=json&pretty=true
```

If not, we will need a config file that is included in the package that we can pull from GitHub whenever `validate-refs` executed.

**Comment by al-niessner** [comment]
@jordanpadams 

As per separate email: comma, semi-colon, or both?

Also, I think NASA-PDS/registry#350 was about comma, semi-colon, or a virtual index that resolved to all of our indices. I do not remember it being about read permissions although that could have distracted us.

**Comment by jordanpadams** [comment]
@al-niessner https://github.com/NASA-PDS/registry/issues/350 was pertaining to enabling this for other users. that being said, an alias index seems to make a lot of sense for something like this.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @al-niessner , the registry-api is using a configuration containing the list of prefixes of the existing indexes (e.g. en,geo,atm,...).

If we had a virtual index aggregating them all I guess we would use it as well but this is not blocking.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Sigh - around the loop one more time. Yes, that is correct Java SDK2 uses list of indices.  However, validate does not because it uses the connection XML file instead of "knowning" the right answer a priori as registry does. In the connection XML file, do you want to use comma, semi-colon, or both for the list? If a separated list in a string attribute is unappealing, then do you want to do a virtual node that does it for us (the "knowing" a priori for everyone that keeps everyone in sync rather than registry knowing a different answer than validate)?

**Comment by jordanpadams** [comment]
@al-niessner this information will not be supplied by the user in their connection XML file because that file is a re-use of the same config from harvest/registr-mgr, which is index-specific. So we will need to maintain this list of available indices in validate similar to registry-api. I would recommend we keep this in a separate config file so we can eventually code up a means of automatically updating that file by grabbing the latest from GitHub or elsewhere. For now, let's just hard code it in a config file.

**Comment by al-niessner** [comment]
@jordanpadams 

Okay, but comma, semi-colon, or both?

**Comment by jordanpadams** [comment]
@al-niessner It is something we will maintain, so whatever you prefer.

**Comment by jordanpadams** [comment]
@al-niessner I just updated this ticket with some Engineering Details about what is expected.

**Comment by al-niessner** [comment]
@jordanpadams 

How ridiculous. Give me all the index names, I will build a connections file, put in the validate jar and use it as the default. Gads.

**Comment by jordanpadams** [comment]
@al-niessner +1 thanks. Per discussions on the sprint review, let's standby and see if the aliases work. That would simplify all of this.

**Comment by jordanpadams** [comment]
@al-niessner tested this out with the new aliasing setup but can't seem to get it to work.

Trying to query for `urn:nasa:pds:context:telescope:parkes.dss49_64m::1.1` with the registry client seems to work against both the `en-registry` and `registry` alias indices:
```
$ pds-registry-client '/en-registry/_search' --data '{"fields":["lidvid"],"query":{"match":{"lidvid":"urn:nasa:pds:context:telescope:parkes.dss49_64m::1.1"}},"_source": false}' --pretty

$ pds-registry-client '/registry/_search' --data '{"fields":["lidvid"],"query":{"match":{"lidvid":"urn:nasa:pds:context:telescope:parkes.dss49_64m::1.1"}},"_source": false}' --pretty
```

When I try with `validate-refs`, it works for `en-registry` but not with `registry`:

From `en-mcp-prod.xml`:
```
<registry_connection index="en-registry">
  ...
```
```
$ validate-refs -a registry-auth.txt -r file:///Users/jpadams/.auth/en-mcp-prod.xml urn:nasa:pds:context:telescope:parkes.dss49_64m::1.1

15:27:15.902 [Thread-0] ERROR gov.nasa.pds.validate.ri.CommandLineInterface - Found duplicate file: /data/pds4/documents/xml_schema/sp/v1/PDS4_SP_1700.sch
15:27:16.143 [Thread-0] ERROR gov.nasa.pds.validate.ri.CommandLineInterface - Found duplicate file: /data/pds4/documents/xml_schema/sp/v1/PDS4_SP_1700.xsd
```

Update for `registry` index:
```
<registry_connection index="registry">
  ...
```
```
$ validate-refs -a registry-auth.txt -r file:///Users/jpadams/.auth/en-mcp-prod.xml urn:nasa:pds:context:telescope:parkes.dss49_64m::1.1

15:28:42.328 [Thread-0] ERROR gov.nasa.pds.validate.ri.CommandLineInterface - Had an error communicating with opensearch
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808) ~[?:?]
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
```

Can you confirm if you are able to access the new `registry` alias index in prod?

**Comment by jordanpadams** [comment]
Also, once we confirm we can query it, can we please hardcode that alias value somewhere for use by validate-refs?

**Comment by al-niessner** [comment]
@jordanpadams 

Am I missing something or some steps? When I run using en-registry, I get lidvid is missing from database. Maybe it changed because it is shared?

Same error with registry. Maybe timeout was because you did access while it was being changed?

**Comment by jordanpadams** [comment]
@al-niessner Are you querying the Prod registry? That is only where the data is loaded.

**Comment by al-niessner** [comment]
@jordanpadams 

Not sure I understand. I am using cognito and using the index en-registry. What else would make it prod?

Ah, when I look closer they have a different gateway and client id. I guess that is what you mean by prod.

**Comment by jordanpadams** [comment]
@al-niessner correct. the gateway and client ID point to a different Cognito.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Still blocked waiting on read access to prod.

**Comment by jordanpadams** [comment]
@al-niessner any status on this?

**Comment by al-niessner** [comment]
@jordanpadams 

Yes. It is our problem. It seems that opensearch people set up a test quickly and they think the SDK is working just fine. I need to reduce the code to something much simpler to figure out what is happening.

**Comment by jordanpadams** [comment]
@al-niessner can we move this to the top of the list?

**Comment by rchenatjpl** [comment]
@jordanpadams Sorry, what is the AOSS registry? How does it affect testing validate? Thanks

**Comment by rchenatjpl** [comment]
@jordanpadams @al-niessner I didn't know validate-refs existed. How do I get authorization, i.e. the contents of the auth-file? Is the "AOSS registry" not the default registry? Thanks

**Comment by jordanpadams** [comment]
@rchenatjpl this is not working as expected at the moment per https://github.com/NASA-PDS/validate/issues/1183, so you can hold off testing this right now. the documentation for this feature is also largely non-existent, so we will work that as part of that other fix.

**Comment by jordanpadams** [comment]
I tested this at PR time and can confirm this works in production. Skipping I&T
