### ISSUE TITLE
validate version 3.5.0-snapshot not working on Windows server

### ISSUE THREAD

**Issue by edguinness** [NASA-PDS-Incubator/validate#868]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

Tried to validate a bundle using version 3.5.0-snapshot with Java 15.0.2 on a Windows server. The following message was displayed on the command window:
Q:\stage\VikingLander\validation>validate -D -v2 -C catalog_v02.xml -R pds4.bundle -r rocks_noc.txt -t Q:\stage\VikingLa
nder\PDS4\urn-nasa-pds-vl_rocks
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.String.repeat(I)Ljava/lang/String;
        at gov.nasa.pds.validate.report.FullReport.end(FullReport.java:172)
        at gov.nasa.pds.validate.report.Report.printHeader(Report.java:145)
        at gov.nasa.pds.validate.ValidateLauncher.setupReport(ValidateLauncher.java:1322)
        at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1683)
        at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1764)
Q:\stage\VikingLander\validation>validate -V

gov.nasa.pds:validate
Version 3.5.0-SNAPSHOT
Release Date: 2024-02-09 18:40:35

The resulting report file was empty.

### 🕵️ Expected behavior

I expected [...]

### 📜 To Reproduce

1.
2.
3.
...

### 🖥 Environment Info

version 3.5.0-snapshot; Java 15.0.2
- Windows server
...

### 🦄 Related requirements

🦄 #xyz

**Comment by edguinness** [comment]
Note that when running 3.5.0 on my Windows 10 laptop with Java 11, I get the issue that is documented in issue #854.

**Comment by jordanpadams** [comment]
@edguinness can you send over the values for your JAVA_HOME and PATH? This is most likely a Java version issue.

**Comment by jordanpadams** [comment]
Per offline discussion, closing as `invalid` since this was an issue with a `JAVA_HOME` system configuration.
